In [ ]:
#1

In [ ]:
import numpy as np

x = np.arange(1,11)

print (x)

print(np.sum(x))

print(np.mean(x))

print(np.std(x))

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
2.8722813232690143


In [ ]:
#2


In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[1])

20


In [ ]:
print(arr[3])

40


In [ ]:
print(arr[2:])

[30 40 50 60]


In [ ]:
print(arr[::-1])

[60 50 40 30 20 10]


In [ ]:
#3

In [ ]:
import numpy as np

a = np.arange(12)

print(a)

print(a.shape)

print(a.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#4

In [ ]:
import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])

print(A)

print(B)

[1 2 3]
[4 5 6]


In [ ]:
np.add(A,B)

array([5, 7, 9])

In [ ]:
np.subtract(B,A)

array([3, 3, 3])

In [ ]:
np.multiply(A,B)

array([ 4, 10, 18])

In [ ]:
np.divide(A,B)

array([0.25, 0.4 , 0.5 ])